-- Creacion de usuario para la BD
-- SE TENDRA TRES TIPOS DE USUARIOS QUE SE CONECTARAN A NUESTRA BD
-- USUARIO DBA: TODOS LOS PRIVILEGIOS
-- USUARIO TECNICO_ADMINISTRATIVO: ALTERA DATOS DE LAS TABLAS
-- USUARIO VISITANTE: SOLO CONSULTA INFORMACION
ALTER SESSION SET "_ORACLE_SCRIPT"=true; -- EJECUTAR SI Y SOLO SI TIENES ORACLE 12C

-- Perfil "CONTROL_PASS" que limita la autenticacion
CREATE PROFILE CONTROL_PASS LIMIT
  FAILED_LOGIN_ATTEMPTS 2
  PASSWORD_LOCK_TIME UNLIMITED
  PASSWORD_LIFE_TIME 1
  PASSWORD_REUSE_TIME 365
  PASSWORD_REUSE_MAX 1
  PASSWORD_GRACE_TIME 1;

-- Perfil "CONTROL_DEVELOPER" que limita los usos de recursos
CREATE PROFILE CONTROL_RECURSOS LIMIT
  SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION 10000
  IDLE_TIME 15
  CONNECT_TIME 60;
  
-- Creando Rol "DBA_SISCAE" y asignando privilegios
CREATE ROLE DBA_SISCAE ;
GRANT CONNECT,RESOURCE TO DBA_SISCAE;

-- Creando Rol "TECNICO_ADMINISTRATIVO" y asignando privilegios
CREATE ROLE TECNICO_ADMINISTRATIVO ;
GRANT CONNECT,SELECT ANY TABLE, 
INSERT ANY TABLE, 
UPDATE ANY TABLE, 
DELETE ANY TABLE TO TECNICO_ADMINISTRATIVO;

-- Creando Rol "VISITANTE" y asignando privilegios
CREATE ROLE VISITANTE ;
GRANT CONNECT,SELECT ANY TABLE TO VISITANTE;

-- Creando primer usuario "USER_DBA"
CREATE USER USER_DBA IDENTIFIED BY "DBA12345"
DEFAULT TABLESPACE  data_proyect
TEMPORARY TABLESPACE  temp_proyect;

GRANT DBA_SISCAE, CONTROL_PASS, CONTROL_RECURSOS TO USER_DBA;

-- Creando tercer usuario "USER_TEA"
CREATE USER USER_TEA IDENTIFIED BY "123"
DEFAULT TABLESPACE  data_proyect
TEMPORARY TABLESPACE  temp_proyect;

GRANT TECNICO_ADMINISTRATIVO, CONTROL_PASS, CONTROL_RECURSOS TO USER_TEA;

-- Creando tercer usuario "USER_VISITANTE"
CREATE USER USER_VISITANTE IDENTIFIED BY "123"
DEFAULT TABLESPACE  data_proyect
TEMPORARY TABLESPACE  temp_proyect;

GRANT VISITANTE, CONTROL_PASS, CONTROL_RECURSOS TO USER_VISITANTE;




